service: sstorage-storage-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${env:ENV}
  region: us-east-1
  timeout: 15
  memorySize: 2048
functions:
  app:
    handler: handler.app
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    # Environment variables
    environment:
      ENV: ${env:ENV}
      ENABLE_DEBUG: ${env:ENABLE_DEBUG}
      SERVER_PORT: ${env:SERVER_PORT}
      MONGODB_URL: ${env:MONGODB_URL}
      CLOUD_SECRET_KEY: ${env:CLOUD_SECRET_KEY}
      CLOUD_ACCESS_KEY_ID: ${env:CLOUD_ACCESS_KEY_ID}
      MULTER_S3_BUCKET: ${env:MULTER_S3_BUCKET}
